# Generated by Django 3.0.9 on 2020-09-01 12:11

import backend.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='account_name')),
                ('account_type', models.CharField(choices=[(backend.utils.enums._AccountTypes(1, 'standard', 'Standard'), 'Standard'), (backend.utils.enums._AccountTypes(2, 'master', 'Master'), 'Master'), (backend.utils.enums._AccountTypes(3, 'vip', 'VIP'), 'VIP')], default=backend.utils.enums._AccountTypes(1, 'standard', 'Standard'), max_length=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
